// <auto-generated />
// Types for commands not generated by source generator

namespace Rulesync.Sdk.DotNet.Models;

using System.Text.Json.Serialization;

/// <summary>
/// Options for fetching remote configurations from CLI.
/// </summary>
public sealed class FetchOptions
{
    /// <summary>
    /// Source repository path (e.g., github:owner/repo/path).
    /// </summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// Local path where files should be saved.
    /// </summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>
    /// Whether to overwrite existing files.
    /// </summary>
    public bool Force { get; set; } = false;

    /// <summary>
    /// GitHub token for authentication.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Whether to enable verbose logging.
    /// </summary>
    public bool Verbose { get; set; } = false;

    /// <summary>
    /// Whether to suppress non-error output.
    /// </summary>
    public bool Silent { get; set; } = false;
}

/// <summary>
/// Result for a single fetched file.
/// </summary>
public sealed class FetchFileResult
{
    /// <summary>
    /// Relative path of the file.
    /// </summary>
    [JsonPropertyName("relativePath")]
    public string RelativePath { get; init; } = string.Empty;

    /// <summary>
    /// Status of the file fetch.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = string.Empty;
}

/// <summary>
/// Summary of fetch operation results.
/// </summary>
public sealed class FetchSummary
{
    /// <summary>
    /// Files that were fetched.
    /// </summary>
    [JsonPropertyName("files")]
    public System.Collections.Generic.List<FetchFileResult> Files { get; init; } = new();
}

/// <summary>
/// Result of initializing a rulesync project.
/// </summary>
public sealed class InitResult
{
    /// <summary>
    /// The configuration file that was created.
    /// </summary>
    [JsonPropertyName("configFile")]
    public InitFileResult? ConfigFile { get; init; }

    /// <summary>
    /// Sample files that were created.
    /// </summary>
    [JsonPropertyName("sampleFiles")]
    public System.Collections.Generic.List<InitFileResult> SampleFiles { get; init; } = new();
}

/// <summary>
/// Options for initializing a rulesync project.
/// </summary>
public sealed class InitOptions
{
    /// <summary>
    /// Path to the configuration file.
    /// </summary>
    public string ConfigPath { get; set; } = string.Empty;

    /// <summary>
    /// Whether to enable verbose logging.
    /// </summary>
    public bool Verbose { get; set; } = false;

    /// <summary>
    /// Whether to suppress non-error output.
    /// </summary>
    public bool Silent { get; set; } = false;
}

/// <summary>
/// Result of managing .gitignore entries.
/// </summary>
public sealed class GitignoreResult
{
    /// <summary>
    /// Number of entries added.
    /// </summary>
    [JsonPropertyName("entriesAdded")]
    public int EntriesAdded { get; init; }
}

/// <summary>
/// Options for managing .gitignore entries.
/// </summary>
public sealed class GitignoreOptions
{
    /// <summary>
    /// Path to the configuration file.
    /// </summary>
    public string ConfigPath { get; set; } = string.Empty;

    /// <summary>
    /// Whether to enable verbose logging.
    /// </summary>
    public bool Verbose { get; set; } = false;

    /// <summary>
    /// Whether to suppress non-error output.
    /// </summary>
    public bool Silent { get; set; } = false;
}

/// <summary>
/// Result of installing skills.
/// </summary>
public sealed class InstallResult
{
    /// <summary>
    /// Number of skills installed.
    /// </summary>
    [JsonPropertyName("installed")]
    public int Installed { get; init; }

    /// <summary>
    /// Number of skills updated.
    /// </summary>
    [JsonPropertyName("updated")]
    public int Updated { get; init; }
}

/// <summary>
/// Options for installing skills.
/// </summary>
public sealed class InstallOptions
{
    /// <summary>
    /// Whether to update existing skills.
    /// </summary>
    public bool Update { get; set; } = false;

    /// <summary>
    /// Whether to fail if lock file is out of sync.
    /// </summary>
    public bool Frozen { get; set; } = false;

    /// <summary>
    /// GitHub token for authentication.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Path to the configuration file.
    /// </summary>
    public string ConfigPath { get; set; } = string.Empty;

    /// <summary>
    /// Whether to enable verbose logging.
    /// </summary>
    public bool Verbose { get; set; } = false;

    /// <summary>
    /// Whether to suppress non-error output.
    /// </summary>
    public bool Silent { get; set; } = false;
}

/// <summary>
/// Result of updating rulesync CLI.
/// </summary>
public sealed class UpdateResult
{
    /// <summary>
    /// Whether an update was available.
    /// </summary>
    [JsonPropertyName("available")]
    public bool Available { get; init; }

    /// <summary>
    /// Current version.
    /// </summary>
    [JsonPropertyName("currentVersion")]
    public string CurrentVersion { get; init; } = string.Empty;

    /// <summary>
    /// Latest version.
    /// </summary>
    [JsonPropertyName("latestVersion")]
    public string LatestVersion { get; init; } = string.Empty;
}

/// <summary>
/// Options for updating rulesync CLI.
/// </summary>
public sealed class UpdateOptions
{
    /// <summary>
    /// Whether to only check for updates without installing.
    /// </summary>
    public bool Check { get; set; } = false;

    /// <summary>
    /// Whether to force update even if already on latest version.
    /// </summary>
    public bool Force { get; set; } = false;

    /// <summary>
    /// GitHub token for authentication.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Whether to enable verbose logging.
    /// </summary>
    public bool Verbose { get; set; } = false;

    /// <summary>
    /// Whether to suppress non-error output.
    /// </summary>
    public bool Silent { get; set; } = false;
}
